language: node_js
node_js:
- 8
- node
- 6
script:
- yarn lint
- yarn test --coverage
cache:
  yarn: true
branches:
  only:
  - master
  # Practical when batching releases
  - next
  - "/^greenkeeper/.*$/"
